FROM python:2.7
RUN apt-get update
RUN apt-get --assume-yes -y install libxml2-dev  libxslt1-dev python-dev zlib1g-dev
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install tshark
RUN pip install lxml trollius logbook py pyshark click
WORKDIR /root
RUN git clone https://github.com/albertomino/challenge.git
RUN mkdir /root/data_traffic
WORKDIR /root/challenge
CMD ["python","capturing_v2.py","--nic","wlp2s0","--dump"]
